name: Fixed Pipeline Challenge
on:
  push:
    branches: [feature/ci-pipeline]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install pytest
      - name: Run version check
        run: pytest --version
